// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEHSsX0GtboeA9-JCvFcxwFL2r3_XHHTw',
    appId: '1:63081763430:web:c70c530c16c19264a193a7',
    messagingSenderId: '63081763430',
    projectId: 'chat-app-9c150',
    authDomain: 'chat-app-9c150.firebaseapp.com',
    storageBucket: 'chat-app-9c150.appspot.com',
    measurementId: 'G-GMMC8RBLJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-muMzfM2tvvRDIaXxiRrz5xIV-UiGXTs',
    appId: '1:63081763430:android:e9c89f57c356750da193a7',
    messagingSenderId: '63081763430',
    projectId: 'chat-app-9c150',
    storageBucket: 'chat-app-9c150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs7k55hhNQee92dqQuANs5K0thHbdLIhM',
    appId: '1:63081763430:ios:ba7160a22130cf36a193a7',
    messagingSenderId: '63081763430',
    projectId: 'chat-app-9c150',
    storageBucket: 'chat-app-9c150.appspot.com',
    iosClientId: '63081763430-aan3lvhn80p6b7lkb64dsva60s2a3sup.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs7k55hhNQee92dqQuANs5K0thHbdLIhM',
    appId: '1:63081763430:ios:ba7160a22130cf36a193a7',
    messagingSenderId: '63081763430',
    projectId: 'chat-app-9c150',
    storageBucket: 'chat-app-9c150.appspot.com',
    iosClientId: '63081763430-aan3lvhn80p6b7lkb64dsva60s2a3sup.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
